<?php
/**
 * Implements hook_menu().
 */
function viamoaccessdenied_menu() {
  $items = array();

  // custom access denied menu item (redirects to login)
  $items['access-denied'] = array(
    'page callback' => 'viamoaccessdenied_access_denied',
    'access callback' => TRUE,   
  );
  $items['page-not-found'] = array(
    'page callback' => 'viamoaccessdenied_page_notfound',
    'access callback' => TRUE,   
  );    
    return $items;
}

/**
 * Page callback for the access denied page. Does a redirect to login page (Taken from r4032login.module)
 */
function viamoaccessdenied_access_denied() {
  global $user;
  if ($user->uid) {
    return MENU_ACCESS_DENIED;
  }

  // The code in drupal_get_destination() doesn't preserve any query string
  // on 403 pages, so reproduce the part we want here.
  $path = $_GET['destination'];
  $query = drupal_http_build_query(drupal_get_query_parameters(NULL, array('q', 'destination')));
  if ($query != '') {
    $path .= '?' . $query;
  }
  $destination = array('destination' => $path);  
  // get_baseurl_with_language function exist in template.php file
  $url = get_baseurl_with_language().'#customer_menu';
  header('Location: ' .$url, TRUE, 302);  
  //header('Location: ' . url('user/login', array('query' => $destination, 'absolute' => TRUE)), TRUE, 302);
  drupal_exit();
}


function viamoaccessdenied_page_notfound(){      
  global $user;
  if ($user->uid) {
    return MENU_ACCESS_DENIED;
  }

  // The code in drupal_get_destination() doesn't preserve any query string
  // on 403 pages, so reproduce the part we want here.
  $path = $_GET['destination'];
  $query = drupal_http_build_query(drupal_get_query_parameters(NULL, array('q', 'destination')));
  if ($query != '') {
    $path .= '?' . $query;
  }
  $destination = array('destination' => $path);
  header('Location: ' . url('404', array('query' => $destination, 'absolute' => TRUE)), TRUE, 302);
  drupal_exit();        
}