<?php
/**
 * Implements hook_menu().
 */
function commerce_add_to_cart_confirmation_extras_menu() {

    $items['add_to_cart/%ctools_js/%'] = array(
        'title' =>'Add to cart',
        'page callback' => 'commerce_add_to_cart_confirmation_extras_add_to_cart',
        'page arguments' => array(1, 2),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}


/**
 * Implements hook_views_api().
 */
function commerce_add_to_cart_confirmation_extras_views_api() {
    return [
        'api' => 3,
        'path' => drupal_get_path('module', 'commerce_add_to_cart_confirmation_extras') . '/views',
    ];
}

/**
 * Add to cart page callback
 */
function commerce_add_to_cart_confirmation_extras_add_to_cart($js, $prod_ids) {
    $product_ids = explode('-', $prod_ids);
    $products = commerce_product_load_multiple($product_ids);
    $commerce_form_id = commerce_cart_add_to_cart_form_id($product_ids);

    // Get the line product
    $line_item = NULL;
    if (!empty($products)) {
        $type = 'product';
        $line_item = commerce_product_line_item_new(reset($products), 1, 0, array(), $type);
        $line_item->data['context']['product_ids'] = array_keys($products);
        $line_item->data['context']['add_to_cart_combine'] = 1;
    }

    $view_mode = 'line_item';
    $form_state = array(
        'title' => '<h4 class="mb-4"><i class="fa mr-2 fa-shopping-cart v-gold-text" aria-hidden="true"></i>'.t('Add this product to your Cart').'</h4>',
        'ajax' => $js,
        're_render' => !$js,
        'no_redirect' => $js,
        'commerce_add_to_cart_confirmation_extras_add_to_cart' => TRUE,
    );
    $form_state['build_info']['args'] = array($line_item, TRUE, array('view_mode' => $view_mode)); // fix view_mode pt field
    $cart_form = drupal_build_form($commerce_form_id, $form_state);
    unset($cart_form['submit']['#prefix']);
    unset($cart_form['submit']['#suffix']);
    unset($cart_form['submit']['#attributes']['class']);
    unset($cart_form['#prefix']);
    unset($cart_form['#suffix']);
    $cart_form['#prefix']='<div class="row col s12">';
    $cart_form['#suffix'] = '</div>';

    $cart_form['checkout']['#attributes']['class'][] ='left';
    $cart_form['submit']['#attributes']['class'][] ='right';
    $cart_form['submit']['#prefix']    = '<div class="modal-footer">';
    $cart_form['checkout']['#suffix'] = '<div class="clearfix"></div></div>';

    $cart_form['products'] = entity_view('commerce_product', $products, $view_mode/*, $GLOBALS['language']->language, 1*/);    //dpm($cart_form);
    if (!$js) {
        return $cart_form;
    }

    ctools_include('modal');
    ctools_include('ajax');
    ctools_add_js('ajax-responder');

    $commands = ctools_modal_form_render($form_state, $cart_form);

    // Handle submitted form.
    if (!empty($form_state['executed'])) {
        $commands = array();
        $commands[] = ctools_modal_command_dismiss();
        drupal_set_message("Your product added to your cart");
        $commands[] = ctools_ajax_command_redirect($_GET['destination']);
    }

    print ajax_render($commands);
}

/**
 *  Implementation of hook_form_BASE_FORM_ID_alter()
 *  alter commerce add to cart form
 *
 */
function commerce_add_to_cart_confirmation_extras_form_commerce_cart_add_to_cart_form_alter(&$form, &$form_state, $form_id) {
    if (!isset($form_state['commerce_add_to_cart_confirmation_extras_add_to_cart'])) {
        return;
    }
    $form['submit']['#value'] = t('Add and Continue Shopping');
    $form['checkout'] = array(
        '#type' => 'submit',
        '#value' => t('Add and View Cart'),
        '#weight' => 51,
    );
    $form['#submit'][] = 'commerce_add_to_cart_confirmation_extras_add_to_cart_submit';
}

/**
 * Add to cart submit handler
 */
function commerce_add_to_cart_confirmation_extras_add_to_cart_submit($form, &$form_state) {
    if ($form_state['values']['op'] != t('Add and View Cart')) return;
    $form_state['redirect'] = $_GET['destination'] = 'cart';
}
