<?php
/**
 * Implements hook_init().
 *  
 */  
function teacherlistgridview_init() {
    if(arg(0)=='teacher-changeview-style') {
        //variable_set('class-gird-list', '');               
    } else {
        if(arg(0)=='teacher') {                       
            if(!(isset($_SESSION['teacher-view-change-flg']) && $_SESSION['teacher-view-change-flg']=='Yes')) {
                $_SESSION['teacher-listView']='hidden';
                $_SESSION['teacher-active-list-view']=' ';
                $_SESSION['teacher-active-grid-view']='active';   
            }                                    
        }        
    }   
}

/**
 * Implements hook_block_info().
 *  
 */
function teacherlistgridview_block_info() {
  $blocks['teach_list_and_grid'] = array(
    'info' => t('Teacher Listing Grid And List'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 *  
 */

function teacherlistgridview_block_view($delta = '') {
  // The $delta parameter tells us which block is being requested.
  switch ($delta) {
    case 'teach_list_and_grid':     
        if(function_exists('teach_ajax_link_page')) {            
            $GridListLink = teach_ajax_link_page();    
            $block['subject'] = t('List and gird view icon');    
            $block['content'] = '';   
            $block['content'] = $GridListLink;    
        } else {
            $block['content'] = '';    
        }
       break;    
   }
  return $block;
}
/**
 * Implements hook_menu().
 *  
 */      
function teacherlistgridview_menu() {             
  $items['ajax-changeview'] = array(
    'title' => 'Ajax Test',
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'teach_ajax_link_page',
    'access arguments' => array('access content'),
  );
 
  $items['teacher-changeview-style/%/%'] = array(
    'title' => 'Ajax test callback',
    'type' => MENU_CALLBACK,
    'page callback' => 'teach_ajax_link_callback',
    'page arguments' => array(1,2),
    'access arguments' => array('access content'),
  );
  
    return $items;
}  

/**
 * Ajax callback to display Toggle List And Grid View School listing View.
 */

function teach_ajax_link_callback($ajax,$type) {           
   
   $_SESSION['teacher-class-gird-list']=$type;
   $_SESSION['teacher-view-change-flg'] = 'Yes';
   
   if ($type=='list') {             
       $_SESSION['teacher-girdView']='hidden';
       $_SESSION['teacher-listView']='display';       
       $_SESSION['teacher-active-grid-view']='';
       $_SESSION['teacher-active-list-view']='active';              
   }
   if ($type=='grid') {             
        $_SESSION['teacher-girdView']='display';
        $_SESSION['teacher-listView']='hidden';       
        $_SESSION['teacher-active-grid-view']='active';
        $_SESSION['teacher-active-list-view']='';              
   }     
   
  drupal_add_js(array('FilterOpenStatus'=> 'NO'), 'setting');
   
  $time='';
  if ($ajax == 'ajax') {
    $commands = array();
    // Ajax command to replace the #ajax-display element with the current time.
    $commands[] = ajax_command_replace('#ajax-display', "<div id='ajax-display'>" . $time . "</div>");            
    // Add a visual "changed" marker to the '#ajax-display' element.
    $commands[] = ajax_command_changed('#ajax-display');        
    //$commands[] = ajax_command_invoke('.products', 'addClass', array('list'));
    $commands[] = ajax_command_invoke('.view-id-teacher', 'trigger', array('RefreshView'));
    $commands[] = ajax_command_invoke('#views-exposed-form-teacher-page', 'clearForm');   
    
    
    $commands[] = ajax_command_replace('#ajax-link-grid', "<div id='ajax-link-grid'>" . $time . "</div>");    
    ajax_deliver(array('#type' => 'ajax', '#commands' => $commands));
  }
  else {
    // No ajax, just replace the html.
    return array(
      '#markup' => $time,
    );
  }
}


/**
 * Callback function that displays Grid And List View Toggle Button .
 */
function teach_ajax_link_page() {    
  //$gridImage = drupal_get_path('theme', 'ukschool')."/img/grid-view.png";
  //$gridList = '<img src="'.$gridImage.'" alt="Grid">'; 
  
 // $ListImage = drupal_get_path('theme', 'ukschool')."/img/list-view-active.png";
  //$List = '<img src="'.$ListImage.'" alt="Grid">'; 
  
  $gridAndList=array();
  $gridAndList[]= array(
    '#type' => 'link',
    '#title' => '<i class="mdi-set mdi-view-list"></i>',
    '#href' => 'teacher-changeview-style/nojs/list',
    '#prefix' => '<div id="ajax-link">'.$List,
    '#suffix' => '</div><div id="ajax-display"></div>',
    '#ajax' => array(
      'effect' => 'fade',
       'progress' => array('type' => 'none'), 
    ),
    '#options' => array(      
      'attributes' => array('class'=>array($_SESSION['teacher-active-list-view'])),       
      'html' => true,
   ),  
      
  );
  $gridAndList[]= array(
    '#type' => 'link',
    '#title' => '<i class="mdi-set mdi-view-module"></i>',
    '#href' => 'teacher-changeview-style/nojs/grid',
    '#prefix' => '<div id="ajax-link-grid">'.$gridList,
    '#suffix' => '</div><div id="ajax-display-grid"></div>',
    '#ajax' => array(
      'effect' => 'fade',
      'progress' => array('type' => 'none'), 
    ),
    '#options' => array(       
       'attributes' => array('class'=>array($_SESSION['teacher-active-grid-view'])),       
       'html' => true,
    ),  
  );  
  return $gridAndList;  
}
?>


