<?php

/**
 * @file
 * Provides an example address field lookup service.
 */

/**
 * Implements hook_addressfield_lookup_service_info().
 */
function addressfield_lookup_example_addressfield_lookup_service_info() {
  return array(
    'example' => array(
      'name' => t('Example'),
      'class' => 'AddressFieldLookupExample',
      'object factory' => 'addressfield_lookup_example_create',
      'description' => t('Provides an example address field lookup service.'),
      'test data' => 'TS1 1ST',
    ),
  );
}

/**
 * Factory function: creates the example lookup service object.
 *
 * @param array $service_info
 *   Config array describing the lookup service.
 * @param string $country
 *   ISO2 code of the country to get addresses in.
 *
 * @return AddressFieldLookupInterface
 *   The instantiated lookup class.
 *
 * @see hook_addressfield_lookup_service_info()
 */
function addressfield_lookup_example_create($service_info, $country = NULL) {
  $example_service = new $service_info['class']();

  // Set a country value if we have one.
  if (!empty($country)) {
    $example_service->setCountry($country);
  }

  return $example_service;
}
